### ISSUE TITLE
doesn't compile

### ISSUE THREAD

**Issue by haashem** [szk-atmosphere/SAParallaxViewControllerSwift#14]
I have installed it manually but compilation failed!

here is shots:
<img width="132" alt="screen shot 2015-09-26 at 10 56 18 am" src="https://cloud.githubusercontent.com/assets/3206748/10116325/910834e0-643d-11e5-8a93-0b9125ece750.png">
<img width="205" alt="screen shot 2015-09-26 at 10 58 22 am" src="https://cloud.githubusercontent.com/assets/3206748/10116326/9b7bd17a-643d-11e5-8c83-ee43afa00b02.png">

**Comment by marty-suzuki** [comment]
hi, @hashemp206
what is your xcode version?

**Comment by haashem** [comment]
I figure it out! My Xcode and swift version is old! Xcode 6.4

تشکر

**Comment by haashem** [comment]
do you have any blog post about how you have implemented this parallaxViewController?

**Comment by marty-suzuki** [comment]
yes, i have. but that is private and written in japanese.

**Comment by haashem** [comment]
I'm trying a custom UICollectionView transition like storehouse. I want to expand selected cell with a decay animation than animate toViewController from within expanded cell.

it seems I can't change UICollectionView `performBatchUpdate:` animationDuration or use UIView animation. 
I want to know how did you handle this custom transition? would you provide me some hint? you can translate part of your doc via http://translate.google.com
