### ISSUE TITLE
Xcode 8.0 No such module 'SABlurImageView'

### ISSUE THREAD

**Issue by git-hwa** [szk-atmosphere/SAParallaxViewControllerSwift#20]
My pod file is here : 

```
target 'RedFive' do
  use_frameworks!

  pod 'SAParallaxViewControllerSwift', :git => 'https://github.com/szk-atmosphere/SAParallaxViewControllerSwift.git', :tag => '2.0.0-beta'
  pod 'SABlurImageView'
  pod 'MisterFusion'

end
```

[I have removed git url from SABlurImageView](https://github.com/marty-suzuki/SABlurImageView/issues/32)

How can I fix this problem?
Thanks

**Comment by marty-suzuki** [comment]
Hi, @lubos08
Thank you for reporting.
Fixed.
Please use [2.0.0](https://github.com/marty-suzuki/SAParallaxViewControllerSwift/tree/2.0.0)

**Comment by git-hwa** [comment]
@marty-suzuki Thanks for your quick fix.
How can I change my pod?

**Comment by marty-suzuki** [comment]
Change Podfile like this.

``` ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'RedFive' do
    pod 'SAParallaxViewControllerSwift'
end
```

Thank you

**Comment by git-hwa** [comment]
It occurs swift compile error...

**Comment by marty-suzuki** [comment]
What swift version do you use?

**Comment by git-hwa** [comment]
swift 3.0

**Comment by git-hwa** [comment]
I set `Use Legacy Swift Language Version` to No, but no luck...

**Comment by marty-suzuki** [comment]
Please try to remove your project's DerivedData.

**Comment by marty-suzuki** [comment]
You might find it this directory.
`~/Library/Developer/Xcode/DerivedData/`

**Comment by git-hwa** [comment]
I did it, but not worked.

**Comment by marty-suzuki** [comment]
What kind of error?

**Comment by git-hwa** [comment]
Have you migrated `:tag => '2.0.0-beta'` to your 2.0.0?

**Comment by git-hwa** [comment]
![screen shot 2016-09-23 at 5 08 09 pm](https://cloud.githubusercontent.com/assets/7583692/18790790/64f81168-81b0-11e6-9eed-e7355c11aaa2.png)

**Comment by marty-suzuki** [comment]
`2.0.0-beta` is for Xcode8 beta X.
`2.0.0` is for Xcode8 GM Seed or Greater.

**Comment by git-hwa** [comment]
I'm using Xcode Version 8.0 (8A218a)

**Comment by marty-suzuki** [comment]
Do you execute `pod update`?

**Comment by git-hwa** [comment]
I have just updated my pod, but not working.
My pod version is `1.0.1`

**Comment by marty-suzuki** [comment]
Please use Cocoapods `1.1.0.rc.2`.

**Comment by git-hwa** [comment]
Just updated to `pod 1.1.0.rc.2`, removed derived data, clean project, but not working yet...
Same swift compile error.

**Comment by marty-suzuki** [comment]
I try to create sample project for swift3 with Cocoapods.
It works fine.
