### ISSUE TITLE
How to use with different image (sizes and aspect ratios?)

### ISSUE THREAD

**Issue by Luke47** [szk-atmosphere/SAParallaxViewControllerSwift#9]
Hi!

First of all great work! Love it.

However, when I try to use my own images the layout is messed up (I just swapped out the images in Images.xcassets).

Is it because of the resolution and/or aspect ratio? What can I do to support all kind of resolutions?

Thank you very much :)

![ios simulator screen shot 04 05 2015 21 53 06](https://cloud.githubusercontent.com/assets/5190003/7461071/f7341020-f2a7-11e4-8821-53b4739cecf4.png)

**Comment by marty-suzuki** [comment]
Hi!
Thank you for your question.

You have to change item height with `UICollectionViewDelegateFlowLayout` like this.

``` swift
extension ViewController: UICollectionViewDelegateFlowLayout {
    func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAtIndexPath indexPath: NSIndexPath) -> CGSize {
        return CGSize(width: UIScreen.mainScreen().bounds.size.width, height: 150)
    }
}
```

Please try it!
Thank you!!

**Comment by Luke47** [comment]
Hi @szk-atmosphere !

Sorry for the late reply and thanks for your help.

Unfortunately, that does not solve the problem. It seems the issue is the blurred label view overlay. When scrolling up, the label view is not entirely blurred anymore as it becomes solid at the bottom. That's why the cells seem to be cut off in the picture i posted. But i tried with a different blurcolor and it's now obvious that not the entirety of the view is blurred in that case.

**Comment by marty-suzuki** [comment]
Hi!
Thank you for replying.

If you don't mind, could you show me your source picture and code or could you tell me your picture size like (width: 000px, height: 000px)?

**Comment by akring** [comment]
Same problem,image size is 500px × 281px

And the code:

``` swift
func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAtIndexPath indexPath: NSIndexPath) -> CGSize {

        let collectionViewWidth = self.view.bounds.size.width
        return CGSize(width: collectionViewWidth, height: collectionViewWidth/1.79)
    }
```

And the screenshots:
![img_1121](https://cloud.githubusercontent.com/assets/6525286/15382228/aeea5574-1dba-11e6-981e-89756091dc8f.jpg)
It worked when I launch this ViewController,as the image above
![img_1122](https://cloud.githubusercontent.com/assets/6525286/15382236/c3c24e7a-1dba-11e6-963a-2b40f5f00489.jpg)
However,when I scrolled the collectionView,some thing goes wrong

**Comment by marty-suzuki** [comment]
I think height of each cells is not enough.
Are those cell ratio same as image ratio?

**Comment by akring** [comment]
You are right man,I replaced these pics with bigger size,and it's ok.Thanks for your reply!
